import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { generateFixtureRelease, validateContent } from "../scripts/content-v3-contract.mjs";
import { fixtureCard, invalidFixtureNames, profiles } from "./fixtures/content-v3/fixtures.mjs";

const project = new URL("../", import.meta.url);

async function root() {
  const directory = await mkdtemp(join(tmpdir(), "rap-atlas-v3-"));
  await mkdir(join(directory, "cards"));
  await mkdir(join(directory, "schemas"));
  for (const name of ["card", "evidence", "review", "media", "content-release"]) await writeFile(join(directory, "schemas", `${name}.schema.json`), await (await import("node:fs/promises")).readFile(new URL(`content-v3/schemas/${name}.schema.json`, project), "utf8"));
  return directory;
}
async function add(rootDirectory, fixture) {
  const cardRoot = join(rootDirectory, "cards", fixture.id); await mkdir(cardRoot, { recursive: true });
  for (const [name, value] of [["card.json", fixture.card], ["evidence.json", fixture.evidence], ["review.json", fixture.review]]) await writeFile(join(cardRoot, name), JSON.stringify(value));
  await writeFile(join(cardRoot, "content.ru.md"), fixture.markdown);
  if (fixture.media) { await writeFile(join(cardRoot, "media.json"), JSON.stringify(fixture.media)); await mkdir(join(cardRoot, "assets")); await writeFile(join(cardRoot, "assets", "example.fixture"), "synthetic fixture"); }
  return cardRoot;
}
async function invalid(name, expected, mutate) { const directory = await root(); const fixture = fixtureCard("sound_direction"); const cardRoot = await add(directory, fixture); await mutate(fixture, cardRoot, directory); const result = await validateContent(directory); await rm(directory, { recursive: true, force: true }); assert.equal(result.ok, false, name); assert.match(result.errors.join("\n"), expected, name); }

test("empty corpus produces deterministic empty release", async () => { const directory = await root(); const one = await generateFixtureRelease(directory); const two = await generateFixtureRelease(directory); await rm(directory, { recursive: true, force: true }); assert.equal(one, two); assert.match(one, /"cards":\[\]/); });
test("all five artificial valid profile fixtures pass and normalize absent media", async () => { const directory = await root(); for (const profile of Object.keys(profiles)) await add(directory, fixtureCard(profile)); const result = await validateContent(directory); await rm(directory, { recursive: true, force: true }); assert.equal(result.ok, true, result.errors.join("\n")); assert.equal(result.cards.length, 5); assert.equal(result.cards.find((card) => card.card.contentProfile === "scene_context").mediaSourceState, "absent"); });
test("named invalid fixtures fail validation", async () => { await invalid("invalid-kind-profile", /schema/, async (fixture, cardRoot) => { fixture.card.kind = "release"; await writeFile(join(cardRoot, "card.json"), JSON.stringify(fixture.card)); }); await invalid("missing-required-file", /missing required file/, async (_fixture, cardRoot) => { await rm(join(cardRoot, "review.json")); }); await invalid("empty-media", /schema/, async (fixture, cardRoot) => { fixture.media.assets = []; await writeFile(join(cardRoot, "media.json"), JSON.stringify(fixture.media)); }); await invalid("invalid-markdown-section", /forbidden section/, async (_fixture, cardRoot) => writeFile(join(cardRoot, "content.ru.md"), "# Example\n\n## Bad {#unknown}")); await invalid("wrong-section-order", /section order/, async (_fixture, cardRoot) => writeFile(join(cardRoot, "content.ru.md"), "# Example\n\n## Make {#make}\ntext\n\n## Sound {#sound}\ntext\n\n## Overview {#overview}\ntext")); await invalid("dangling-claim", /dangling claim marker/, async (_fixture, cardRoot) => writeFile(join(cardRoot, "content.ru.md"), "# Example\n\n## Overview {#overview}\n<!-- claims: missing -->\ntext\n\n## Sound {#sound}\ntext\n\n## Make {#make}\ntext")); await invalid("dangling-relation", /dangling relation/, async (fixture, cardRoot) => { fixture.card.relations = [{ id: "relation-example", type: "branch-of", targetId: "missing-target", claimIds: ["claim-example"] }]; await writeFile(join(cardRoot, "card.json"), JSON.stringify(fixture.card)); }); await invalid("cyclic-branch-relation", /branch relation cycle/, async (fixture, cardRoot, directory) => { const other = fixtureCard("sound_direction", "example-cycle-target", false); other.card.relations = [{ id: "relation-back", type: "branch-of", targetId: fixture.id, claimIds: ["claim-example"] }]; fixture.card.relations = [{ id: "relation-forward", type: "branch-of", targetId: other.id, claimIds: ["claim-example"] }]; await writeFile(join(cardRoot, "card.json"), JSON.stringify(fixture.card)); await add(directory, other); }); await invalid("path-traversal", /path traversal/, async (fixture, cardRoot) => { fixture.media.assets[0].path = "../outside.fixture"; await writeFile(join(cardRoot, "media.json"), JSON.stringify(fixture.media)); }); await invalid("incompatible-schema-version", /schema/, async (fixture, cardRoot) => { fixture.card.schemaVersion = "2.0.0"; await writeFile(join(cardRoot, "card.json"), JSON.stringify(fixture.card)); }); await invalid("unsafe-raw-html", /raw HTML/, async (_fixture, cardRoot) => writeFile(join(cardRoot, "content.ru.md"), "# Example\n\n## Overview {#overview}\n<div>unsafe</div>\n\n## Sound {#sound}\ntext\n\n## Make {#make}\ntext")); assert.equal(invalidFixtureNames.length, 11); });
test("assets without a media manifest are rejected", async () => { await invalid("assets-without-media", /assets require media/, async (_fixture, cardRoot) => { await rm(join(cardRoot, "media.json")); await mkdir(join(cardRoot, "assets"), { recursive: true }); }); });
test("dangling source and evidence references are rejected", async () => { await invalid("dangling-source", /dangling source/, async (fixture, cardRoot) => { fixture.evidence.evidence[0].sourceId = "missing-source"; await writeFile(join(cardRoot, "evidence.json"), JSON.stringify(fixture.evidence)); }); await invalid("dangling-evidence", /dangling evidence/, async (fixture, cardRoot) => { fixture.evidence.claims[0].evidenceIds = ["missing-evidence"]; await writeFile(join(cardRoot, "evidence.json"), JSON.stringify(fixture.evidence)); }); });
test("production content root stays empty and outside the current client graph", async () => { const result = await validateContent(fileURLToPath(new URL("../content-v3", import.meta.url))); const appSource = await readFile(new URL("../app/AtlasApp.tsx", import.meta.url), "utf8"); assert.equal(result.ok, true, result.errors.join("\n")); assert.equal(result.cards.length, 0); assert.doesNotMatch(appSource, /content-v3/); });
